---
title: "Gradebook"
author: "Nate Wells"
date: "10/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r}
exams<-read_excel("Exam Grades.xlsx")[1:18,]
slack<-read_excel("Slack Participation.xlsx")[1:18,]
homework <- read_csv("Homework.csv")[1:18,]
project <- read_excel("Project.xlsx")[1:18,]
```

```{r}
gradebook <- inner_join(exams,slack, by = c("reed_id", "first_name", "last_name")) %>% 
  inner_join(homework, by = c("reed_id", "first_name", "last_name")) %>% 
  inner_join(project, by = c("reed_id", "first_name", "last_name")) %>% 
  select(reed_id, first_name, last_name, Midterm_1_pct, Midterm_2_pct, N_participation, hw_pct, Project_Grade)
```

```{r}
gradebook <- gradebook %>% rowwise() %>% mutate(participation_score = min(N_participation, 26)/26)
gradebook <- gradebook %>% mutate(midterm_total = (Midterm_1_pct + Midterm_2_pct)/2)
```

```{r}
weight_names <-c("homework", "midterm", "participation", "project") 
weights  <- c(.4, .25, .05, .3)
sum(weights)
```

```{r}
gradebook <- gradebook %>% mutate(score = hw_pct*weights[1] + midterm_total*weights[2]+ participation_score*weights[3] + Project_Grade*weights[4])
```


