---
title: "How Old"
author: "Nate Wells"
date: "8/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
g1_id <- c("Ngoc", "Rohan", "Bhav", "Maxwell")
g2_id <- c("Group 37")
g3_id <- c("Simon", "Isabelle", "Ingrid")
g4_id <- c("Robin", "Taylor", "Arai")
g5_id <- c("Straight Up Vibes")
```

```{r}
g1 <- c(34, 32, 32, 30, 50, 36, 58, 36)
g2 <- c(38, 30, 32, 35, 55, 41, 61, 34)
g3 <- c(38, 41, 36, 33, 50, 36, 56, 41)
g4_2 <- c(50.5, 35.7, 37.1, 37.4, 83.1, 39.5, 94.5, 45.2)
g4 <- c(39.25, 35, 36, 36, 48, 37, 52, 39)
g5 <- c(35, 32, 34, 33, 39, 35, 55, 36)
nate <- c(31, 33, 35, 34, 31, 32, 56, 36)
how_old.net <- c(35, 29, 36, 31, 51, 36, 56, 39)
names <-   c("Nate", "Luda", "David K", "Kelly", "Kyle", "Angelica", "Dave P", "Andrew")
```

```{r}
age <- data.frame(names = factor(names, levels = names),  nate, g1, g2, g3, g4, g5, how_old.net)
```

```{r}
long_age <- age %>% pivot_longer(cols = !names, values_to = "estimate") 
```

```{r eval = F}
color <- c("nate" = "red", "how_old"="blue")
ggplot(long_age, aes(x = names, y = estimate))+geom_point()+geom_point(data = long_age %>% filter(name == "nate"), aes(x = names, y = estimate, color = "nate"))+
  geom_point(data = long_age %>% filter(name == "how_old"), aes(x = names, y = estimate, color = "how_old"))+
  labs(title = "Estimates for Reed Faculty Age",
       caption = "Based on photos from https://www.reed.edu/faculty-profiles/")+
  theme(legend.title = element_blank())
```


```{r}
my_colors <- rev(c('red', '#9ecae1','#6baed6','#4292c6','#2171b5','#08519c','#08306b'))
ggplot(long_age, aes(x = names, y = estimate, color = name))+geom_jitter(size = 2, width = 0.15, height = 0)+
  labs(title = "Estimates for Reed Faculty Age",
       caption = "Based on photos from https://www.reed.edu/faculty-profiles/")+
  theme(legend.title = element_blank()) +scale_color_manual(values = my_colors)
```